# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fbbba4bf8682731865e8549ec72c351e176a1a71047d92b63ba97e7a1caca206c1c783302df31c79335e5a477820be6eca150cc5357e91962bf786b6da20fe9

test:
  secret_key_base: 2e93f2e03184b6b2bc0aef31eaa1749ecc4c0f60063e4ce95204340e3306163afa091f740a0f97134bd6b08559bdc935b5559ff64c7918cc3dfc4e253f938fcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
